CC = cc

run:
	$(CC) -Werror -Wall -Wextra -o main powerbuffer.c && ./main

comp:
	$(CC) -Werror -Wall -Wextra -o main powerbuffer.c

unsafe:
	$(CC) -o main powerbuffer.c && ./main

clean:
	rm -rf ./main
