CC = cc

run:
	$(CC) -Wall -Wextra -Werror -Wnull-dereference -o main main.c && ./main

comp:
	$(CC) -Wall -Wextra -Werror -o main main.c && ./main

unsafe:
	$(CC) -o main main.c && ./main

clean:
	rm -rf ./main
